### ISSUE TITLE
croyaGameContext

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infcroya#3]
In the future there has to be much added to gamecontext.cpp, therefore I suggest to create a own class for Infcroya.

**Comment by yavl** [comment]
I don't think that CGameContext is meant to be replaced/be a base class. We just need to be strict with begin-end comments this time.

**Comment by teoman002** [comment]
What are your thoughts on a helper class named CroyaGameContext.cpp that is created when GameContext is constructed and destroyed?

That helper class can receive pointer to:
- m_pServer, m_pConsole, m_Collision, m_Tuning,m_pGameServer

It gets access to all variables of the base class through inheritance or reference.

Is there a reason why you think, that does not work as intended?
